package com.exence.finance.modules.statistics.dto.admin;

public enum AdminWidgetType {
    DAILY_ACTIVE_USERS,
    MONTHLY_ACTIVE_USERS,
    TRANSACTION_VELOCITY,
    DATABASE_GROWTH_SUMMARY,
    CURRENCY_DISTRIBUTION,
    AVG_TRANSACTIONS_PER_USER,
    TRANSACTION_TYPE_DISTRIBUTION,
    TOP_ACTIVE_USERS,
    EMAIL_VERIFICATION_RATE
}
