import { TranslationCode } from '../../../shared/i18n/translation-types';

export enum MaterialIcon {
	// Food & Dining
	LOCAL_GROCERY_STORE = 'LOCAL_GROCERY_STORE',
	SHOPPING_BASKET = 'SHOPPING_BASKET',
	KITCHEN = 'KITCHEN',
	SKILLET = 'SKILLET',
	EGG = 'EGG',
	NUTRITION = 'NUTRITION',
	RESTAURANT = 'RESTAURANT',
	RESTAURANT_MENU = 'RESTAURANT_MENU',
	GROCERY = 'GROCERY',
	LUNCH_DINING = 'LUNCH_DINING',
	DINNER_DINING = 'DINNER_DINING',
	FASTFOOD = 'FASTFOOD',
	LOCAL_PIZZA = 'LOCAL_PIZZA',
	LOCAL_CAFE = 'LOCAL_CAFE',
	BAKERY_DINING = 'BAKERY_DINING',
	CAKE = 'CAKE',
	ICECREAM = 'ICECREAM',
	LOCAL_BAR = 'LOCAL_BAR',
	WINE_BAR = 'WINE_BAR',
	LIQUOR = 'LIQUOR',

	// Housing & Utilities
	HOME = 'HOME',
	HOUSE = 'HOUSE',
	APARTMENT = 'APARTMENT',
	COTTAGE = 'COTTAGE',
	GARAGE_HOME = 'GARAGE_HOME',
	BED = 'BED',
	CHAIR = 'CHAIR',
	CONSTRUCTION = 'CONSTRUCTION',
	PLUMBING = 'PLUMBING',
	ELECTRICAL_SERVICES = 'ELECTRICAL_SERVICES',
	MOP = 'MOP',
	LIGHTBULB = 'LIGHTBULB',
	BOLT = 'BOLT',
	WATER_DROP = 'WATER_DROP',
	MODE_HEAT = 'MODE_HEAT',
	THERMOMETER = 'THERMOMETER',
	ENERGY_SAVINGS_LEAF = 'ENERGY_SAVINGS_LEAF',
	RECYCLING = 'RECYCLING',
	ROUTER = 'ROUTER',
	WIFI = 'WIFI',

	// Transport & Travel
	DIRECTIONS_CAR = 'DIRECTIONS_CAR',
	MOTORCYCLE = 'MOTORCYCLE',
	SCOOTER = 'SCOOTER',
	PEDAL_BIKE = 'PEDAL_BIKE',
	LOCAL_GAS_STATION = 'LOCAL_GAS_STATION',
	EV_STATION = 'EV_STATION',
	LOCAL_PARKING = 'LOCAL_PARKING',
	AUTO_TOWING = 'AUTO_TOWING',
	LOCAL_TAXI = 'LOCAL_TAXI',
	AIRPORT_SHUTTLE = 'AIRPORT_SHUTTLE',
	DIRECTIONS_BUS = 'DIRECTIONS_BUS',
	COMMUTE = 'COMMUTE',
	TRAIN = 'TRAIN',
	SUBWAY = 'SUBWAY',
	TRAM = 'TRAM',
	DIRECTIONS_BOAT = 'DIRECTIONS_BOAT',
	FLIGHT = 'FLIGHT',
	AIRPLANE_TICKET = 'AIRPLANE_TICKET',
	TRANSIT_TICKET = 'TRANSIT_TICKET',
	MAP = 'MAP',

	// Shopping & Apparel
	STORE = 'STORE',
	SHOPPING_CART = 'SHOPPING_CART',
	SHOPPING_BAG = 'SHOPPING_BAG',
	SELL = 'SELL',
	PERCENT = 'PERCENT',
	RECEIPT = 'RECEIPT',
	CARD_GIFTCARD = 'CARD_GIFTCARD',
	SEND_MONEY = 'SEND_MONEY',
	APPAREL = 'APPAREL',
	CHECKROOM = 'CHECKROOM',
	STYLER = 'STYLER',
	LAUNDRY = 'LAUNDRY',
	EYEGLASSES = 'EYEGLASSES',
	WATCH = 'WATCH',
	DIAMOND = 'DIAMOND',
	BACKPACK = 'BACKPACK',
	UMBRELLA = 'UMBRELLA',
	SMARTPHONE = 'SMARTPHONE',
	LAPTOP = 'LAPTOP',
	PRINT = 'PRINT',

	// Health & Beauty
	LOCAL_HOSPITAL = 'LOCAL_HOSPITAL',
	MEDICAL_SERVICES = 'MEDICAL_SERVICES',
	HEALTH_AND_SAFETY = 'HEALTH_AND_SAFETY',
	EMERGENCY = 'EMERGENCY',
	LOCAL_PHARMACY = 'LOCAL_PHARMACY',
	MEDICATION = 'MEDICATION',
	VACCINES = 'VACCINES',
	HEALING = 'HEALING',
	MONITOR_HEART = 'MONITOR_HEART',
	DENTISTRY = 'DENTISTRY',
	PSYCHOLOGY = 'PSYCHOLOGY',
	CLEAN_HANDS = 'CLEAN_HANDS',
	WASH = 'WASH',
	BRUSH = 'BRUSH',
	FACE = 'FACE',
	CONTENT_CUT = 'CONTENT_CUT',
	SPA = 'SPA',
	SELF_IMPROVEMENT = 'SELF_IMPROVEMENT',
	FITNESS_CENTER = 'FITNESS_CENTER',
	POOL = 'POOL',

	// Family & Education
	FAMILY_RESTROOM = 'FAMILY_RESTROOM',
	PREGNANT_WOMAN = 'PREGNANT_WOMAN',
	DIVERSITY_3 = 'DIVERSITY_3',
	DIVERSITY_1 = 'DIVERSITY_1',
	CHILD_CARE = 'CHILD_CARE',
	BABY_CHANGING_STATION = 'BABY_CHANGING_STATION',
	STROLLER = 'STROLLER',
	CRIB = 'CRIB',
	CHILD_FRIENDLY = 'CHILD_FRIENDLY',
	ESCALATOR_WARNING = 'ESCALATOR_WARNING',
	TOYS = 'TOYS',
	VIDEOGAME_ASSET = 'VIDEOGAME_ASSET',
	CASTLE = 'CASTLE',
	SENTIMENT_SATISFIED = 'SENTIMENT_SATISFIED',
	PETS = 'PETS',
	CRUELTY_FREE = 'CRUELTY_FREE',
	ELDERLY = 'ELDERLY',
	SCHOOL = 'SCHOOL',
	MENU_BOOK = 'MENU_BOOK',
	HISTORY_2 = 'HISTORY_2',

	// Entertainment & Hobbies
	MOVIE = 'MOVIE',
	THEATERS = 'THEATERS',
	LIVE_TV = 'LIVE_TV',
	CAMERA_ALT = 'CAMERA_ALT',
	IMAGESMODE = 'IMAGESMODE',
	HEADPHONES = 'HEADPHONES',
	MUSIC_NOTE = 'MUSIC_NOTE',
	PIANO = 'PIANO',
	SPORTS_ESPORTS = 'SPORTS_ESPORTS',
	EXTENSION = 'EXTENSION',
	CASINO = 'CASINO',
	THEATER_COMEDY = 'THEATER_COMEDY',
	BOOK = 'BOOK',
	SPORTS_SOCCER = 'SPORTS_SOCCER',
	SPORTS_BASKETBALL = 'SPORTS_BASKETBALL',
	SPORTS_TENNIS = 'SPORTS_TENNIS',
	HIKING = 'HIKING',
	KAYAKING = 'KAYAKING',
	DECK = 'DECK',
	EVENT_SEAT = 'EVENT_SEAT',

	// Finances
	WORK = 'WORK',
	PAID = 'PAID',
	PRICE_CHECK = 'PRICE_CHECK',
	MONEY_BAG = 'MONEY_BAG',
	ACCOUNT_BALANCE = 'ACCOUNT_BALANCE',
	WALLET = 'WALLET',
	ACCOUNT_BALANCE_WALLET = 'ACCOUNT_BALANCE_WALLET',
	EURO = 'EURO',
	ADD_CARD = 'ADD_CARD',
	FINANCE_CHIP = 'FINANCE_CHIP',
	CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE',
	TOLL = 'TOLL',
	TRENDING_UP = 'TRENDING_UP',
	TRENDING_DOWN = 'TRENDING_DOWN',
	PRICE_CHANGE = 'PRICE_CHANGE',
	PIE_CHART = 'PIE_CHART',
	BAR_CHART = 'BAR_CHART',
	CALCULATE = 'CALCULATE',
	RECEIPT_LONG = 'RECEIPT_LONG',
	REQUEST_QUOTE = 'REQUEST_QUOTE',

	// Others
	EVENT = 'EVENT',
	SCHEDULE = 'SCHEDULE',
	CELEBRATION = 'CELEBRATION',
	MAIL = 'MAIL',
	NOTIFICATIONS = 'NOTIFICATIONS',
	PUBLIC = 'PUBLIC',
	CLOUD = 'CLOUD',
	LOCK = 'LOCK',
	KEY = 'KEY',
	VERIFIED = 'VERIFIED',
	HELP = 'HELP',
	STAR = 'STAR',
	FAVORITE = 'FAVORITE',
	BOOKMARK = 'BOOKMARK',
	FLAG = 'FLAG',
	BROWSE = 'BROWSE',
	DESCRIPTION = 'DESCRIPTION',
	BUILD = 'BUILD',
	KEYBOARD = 'KEYBOARD',
	CANCEL = 'CANCEL',
}

interface MaterialIconInfo {
	icon: MaterialIcon;
	tooltip: TranslationCode;
}

enum MaterialIconCategory {
	FOOD_AND_DINING = 'Food & Dining',
	HOUSING_AND_UTILITIES = 'Housing & Utilities',
	TRANSPORT_AND_TRAVEL = 'Transport & Travel',
	SHOPPING_AND_APPAREL = 'Shopping & Apparel',
	HEALTH_AND_BEAUTY = 'Health & Beauty',
	FAMILY_AND_EDUCATION = 'Family & Education',
	ENTERTAINMENT_AND_HOBBIES = 'Entertainment & Hobbies',
	FINANCES = 'Finances',
	OTHERS = 'Others',
}

const MATERIAL_ICON_CATEGORY_DATA: Record<MaterialIconCategory, TranslationCode> = {
	[MaterialIconCategory.FOOD_AND_DINING]: 'icons.categories.food',
	[MaterialIconCategory.HOUSING_AND_UTILITIES]: 'icons.categories.housing',
	[MaterialIconCategory.TRANSPORT_AND_TRAVEL]: 'icons.categories.travel',
	[MaterialIconCategory.SHOPPING_AND_APPAREL]: 'icons.categories.shopping',
	[MaterialIconCategory.HEALTH_AND_BEAUTY]: 'icons.categories.health',
	[MaterialIconCategory.FAMILY_AND_EDUCATION]: 'icons.categories.family',
	[MaterialIconCategory.ENTERTAINMENT_AND_HOBBIES]: 'icons.categories.entertainment',
	[MaterialIconCategory.FINANCES]: 'icons.categories.finances',
	[MaterialIconCategory.OTHERS]: 'icons.categories.others',
};

interface MaterialIconCategoryInfo {
	name: TranslationCode;
	icons: MaterialIconInfo[];
}

export const CategorizedMaterialIcons: MaterialIconCategoryInfo[] = [
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.FOOD_AND_DINING],
		icons: [
			{ icon: MaterialIcon.LOCAL_GROCERY_STORE, tooltip: 'icons.localConvenienceStore' },
			{ icon: MaterialIcon.SHOPPING_BASKET, tooltip: 'icons.shoppingBasket' },
			{ icon: MaterialIcon.KITCHEN, tooltip: 'icons.fridge' },
			{ icon: MaterialIcon.SKILLET, tooltip: 'icons.skillet' },
			{ icon: MaterialIcon.EGG, tooltip: 'icons.egg' },
			{ icon: MaterialIcon.NUTRITION, tooltip: 'icons.nutrition' },
			{ icon: MaterialIcon.RESTAURANT, tooltip: 'icons.restaurant' },
			{ icon: MaterialIcon.RESTAURANT_MENU, tooltip: 'icons.menu' },
			{ icon: MaterialIcon.GROCERY, tooltip: 'icons.groceries' },
			{ icon: MaterialIcon.LUNCH_DINING, tooltip: 'icons.lunch' },
			{ icon: MaterialIcon.DINNER_DINING, tooltip: 'icons.dinner' },
			{ icon: MaterialIcon.FASTFOOD, tooltip: 'icons.fastfood' },
			{ icon: MaterialIcon.LOCAL_PIZZA, tooltip: 'icons.pizza' },
			{ icon: MaterialIcon.LOCAL_CAFE, tooltip: 'icons.cafe' },
			{ icon: MaterialIcon.BAKERY_DINING, tooltip: 'icons.bakery' },
			{ icon: MaterialIcon.CAKE, tooltip: 'icons.cake' },
			{ icon: MaterialIcon.ICECREAM, tooltip: 'icons.iceCream' },
			{ icon: MaterialIcon.LOCAL_BAR, tooltip: 'icons.bar' },
			{ icon: MaterialIcon.WINE_BAR, tooltip: 'icons.wineBar' },
			{ icon: MaterialIcon.LIQUOR, tooltip: 'icons.liquor' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.HOUSING_AND_UTILITIES],
		icons: [
			{ icon: MaterialIcon.HOME, tooltip: 'icons.home' },
			{ icon: MaterialIcon.HOUSE, tooltip: 'icons.house' },
			{ icon: MaterialIcon.APARTMENT, tooltip: 'icons.apartment' },
			{ icon: MaterialIcon.COTTAGE, tooltip: 'icons.cottage' },
			{ icon: MaterialIcon.GARAGE_HOME, tooltip: 'icons.garage' },
			{ icon: MaterialIcon.BED, tooltip: 'icons.bed' },
			{ icon: MaterialIcon.CHAIR, tooltip: 'icons.chair' },
			{ icon: MaterialIcon.CONSTRUCTION, tooltip: 'icons.construction' },
			{ icon: MaterialIcon.PLUMBING, tooltip: 'icons.plumbing' },
			{ icon: MaterialIcon.ELECTRICAL_SERVICES, tooltip: 'icons.electricalServices' },
			{ icon: MaterialIcon.MOP, tooltip: 'icons.mop' },
			{ icon: MaterialIcon.LIGHTBULB, tooltip: 'icons.lightbulb' },
			{ icon: MaterialIcon.BOLT, tooltip: 'icons.bolt' },
			{ icon: MaterialIcon.WATER_DROP, tooltip: 'icons.waterDrop' },
			{ icon: MaterialIcon.MODE_HEAT, tooltip: 'icons.fire' },
			{ icon: MaterialIcon.THERMOMETER, tooltip: 'icons.thermometer' },
			{ icon: MaterialIcon.ENERGY_SAVINGS_LEAF, tooltip: 'icons.energySavingLeaf' },
			{ icon: MaterialIcon.RECYCLING, tooltip: 'icons.recycling' },
			{ icon: MaterialIcon.ROUTER, tooltip: 'icons.router' },
			{ icon: MaterialIcon.WIFI, tooltip: 'icons.wifi' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.TRANSPORT_AND_TRAVEL],
		icons: [
			{ icon: MaterialIcon.DIRECTIONS_CAR, tooltip: 'icons.car' },
			{ icon: MaterialIcon.MOTORCYCLE, tooltip: 'icons.motorcycle' },
			{ icon: MaterialIcon.SCOOTER, tooltip: 'icons.scrooter' },
			{ icon: MaterialIcon.PEDAL_BIKE, tooltip: 'icons.pedalBike' },
			{ icon: MaterialIcon.LOCAL_GAS_STATION, tooltip: 'icons.gasStation' },
			{ icon: MaterialIcon.EV_STATION, tooltip: 'icons.electricCharger' },
			{ icon: MaterialIcon.LOCAL_PARKING, tooltip: 'icons.parking' },
			{ icon: MaterialIcon.AUTO_TOWING, tooltip: 'icons.towing' },
			{ icon: MaterialIcon.LOCAL_TAXI, tooltip: 'icons.taxi' },
			{ icon: MaterialIcon.AIRPORT_SHUTTLE, tooltip: 'icons.airportShuttle' },
			{ icon: MaterialIcon.DIRECTIONS_BUS, tooltip: 'icons.bus' },
			{ icon: MaterialIcon.COMMUTE, tooltip: 'icons.commute' },
			{ icon: MaterialIcon.TRAIN, tooltip: 'icons.train' },
			{ icon: MaterialIcon.SUBWAY, tooltip: 'icons.subway' },
			{ icon: MaterialIcon.TRAM, tooltip: 'icons.tram' },
			{ icon: MaterialIcon.DIRECTIONS_BOAT, tooltip: 'icons.boat' },
			{ icon: MaterialIcon.FLIGHT, tooltip: 'icons.flight' },
			{ icon: MaterialIcon.AIRPLANE_TICKET, tooltip: 'icons.airplaneTicket' },
			{ icon: MaterialIcon.TRANSIT_TICKET, tooltip: 'icons.transitTicket' },
			{ icon: MaterialIcon.MAP, tooltip: 'icons.map' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.SHOPPING_AND_APPAREL],
		icons: [
			{ icon: MaterialIcon.STORE, tooltip: 'icons.store' },
			{ icon: MaterialIcon.SHOPPING_CART, tooltip: 'icons.shoppingCart' },
			{ icon: MaterialIcon.SHOPPING_BAG, tooltip: 'icons.shoppingBag' },
			{ icon: MaterialIcon.SELL, tooltip: 'icons.priceTag' },
			{ icon: MaterialIcon.PERCENT, tooltip: 'icons.percent' },
			{ icon: MaterialIcon.RECEIPT, tooltip: 'icons.receipt' },
			{ icon: MaterialIcon.CARD_GIFTCARD, tooltip: 'icons.giftcard' },
			{ icon: MaterialIcon.SEND_MONEY, tooltip: 'icons.sendMoney' },
			{ icon: MaterialIcon.APPAREL, tooltip: 'icons.apparel' },
			{ icon: MaterialIcon.CHECKROOM, tooltip: 'icons.checkroom' },
			{ icon: MaterialIcon.STYLER, tooltip: 'icons.styler' },
			{ icon: MaterialIcon.LAUNDRY, tooltip: 'icons.laundry' },
			{ icon: MaterialIcon.EYEGLASSES, tooltip: 'icons.glasses' },
			{ icon: MaterialIcon.WATCH, tooltip: 'icons.watch' },
			{ icon: MaterialIcon.DIAMOND, tooltip: 'icons.diamond' },
			{ icon: MaterialIcon.BACKPACK, tooltip: 'icons.backpack' },
			{ icon: MaterialIcon.UMBRELLA, tooltip: 'icons.umbrella' },
			{ icon: MaterialIcon.SMARTPHONE, tooltip: 'icons.smartphone' },
			{ icon: MaterialIcon.LAPTOP, tooltip: 'icons.laptop' },
			{ icon: MaterialIcon.PRINT, tooltip: 'icons.printer' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.HEALTH_AND_BEAUTY],
		icons: [
			{ icon: MaterialIcon.LOCAL_HOSPITAL, tooltip: 'icons.hospital' },
			{ icon: MaterialIcon.MEDICAL_SERVICES, tooltip: 'icons.medialServices' },
			{ icon: MaterialIcon.HEALTH_AND_SAFETY, tooltip: 'icons.health' },
			{ icon: MaterialIcon.EMERGENCY, tooltip: 'icons.emergency' },
			{ icon: MaterialIcon.LOCAL_PHARMACY, tooltip: 'icons.pharmacy' },
			{ icon: MaterialIcon.MEDICATION, tooltip: 'icons.medication' },
			{ icon: MaterialIcon.VACCINES, tooltip: 'icons.vaccines' },
			{ icon: MaterialIcon.HEALING, tooltip: 'icons.patches' },
			{ icon: MaterialIcon.MONITOR_HEART, tooltip: 'icons.heartMonitor' },
			{ icon: MaterialIcon.DENTISTRY, tooltip: 'icons.tooth' },
			{ icon: MaterialIcon.PSYCHOLOGY, tooltip: 'icons.psychology' },
			{ icon: MaterialIcon.CLEAN_HANDS, tooltip: 'icons.handwash' },
			{ icon: MaterialIcon.WASH, tooltip: 'icons.wash' },
			{ icon: MaterialIcon.BRUSH, tooltip: 'icons.brush' },
			{ icon: MaterialIcon.FACE, tooltip: 'icons.face' },
			{ icon: MaterialIcon.CONTENT_CUT, tooltip: 'icons.scissors' },
			{ icon: MaterialIcon.SPA, tooltip: 'icons.spa' },
			{ icon: MaterialIcon.SELF_IMPROVEMENT, tooltip: 'icons.mediation' },
			{ icon: MaterialIcon.FITNESS_CENTER, tooltip: 'icons.dumbbell' },
			{ icon: MaterialIcon.POOL, tooltip: 'icons.swim' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.FAMILY_AND_EDUCATION],
		icons: [
			{ icon: MaterialIcon.FAMILY_RESTROOM, tooltip: 'icons.family' },
			{ icon: MaterialIcon.PREGNANT_WOMAN, tooltip: 'icons.pregnantWoman' },
			{ icon: MaterialIcon.DIVERSITY_3, tooltip: 'icons.closeupFamily' },
			{ icon: MaterialIcon.DIVERSITY_1, tooltip: 'icons.familyHeart' },
			{ icon: MaterialIcon.CHILD_CARE, tooltip: 'icons.child' },
			{ icon: MaterialIcon.BABY_CHANGING_STATION, tooltip: 'icons.babyChangingStation' },
			{ icon: MaterialIcon.STROLLER, tooltip: 'icons.stroller' },
			{ icon: MaterialIcon.CRIB, tooltip: 'icons.crib' },
			{ icon: MaterialIcon.CHILD_FRIENDLY, tooltip: 'icons.childFriendly' },
			{ icon: MaterialIcon.ESCALATOR_WARNING, tooltip: 'icons.familyOfTwo' },
			{ icon: MaterialIcon.TOYS, tooltip: 'icons.toy' },
			{ icon: MaterialIcon.VIDEOGAME_ASSET, tooltip: 'icons.oldGameController' },
			{ icon: MaterialIcon.CASTLE, tooltip: 'icons.castle' },
			{ icon: MaterialIcon.SENTIMENT_SATISFIED, tooltip: 'icons.smile' },
			{ icon: MaterialIcon.PETS, tooltip: 'icons.pet' },
			{ icon: MaterialIcon.CRUELTY_FREE, tooltip: 'icons.bunny' },
			{ icon: MaterialIcon.ELDERLY, tooltip: 'icons.elderly' },
			{ icon: MaterialIcon.SCHOOL, tooltip: 'icons.education' },
			{ icon: MaterialIcon.MENU_BOOK, tooltip: 'icons.book' },
			{ icon: MaterialIcon.HISTORY_2, tooltip: 'icons.time' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.ENTERTAINMENT_AND_HOBBIES],
		icons: [
			{ icon: MaterialIcon.MOVIE, tooltip: 'icons.movie' },
			{ icon: MaterialIcon.THEATERS, tooltip: 'icons.theaterSymbol' },
			{ icon: MaterialIcon.LIVE_TV, tooltip: 'icons.tv' },
			{ icon: MaterialIcon.CAMERA_ALT, tooltip: 'icons.camera' },
			{ icon: MaterialIcon.IMAGESMODE, tooltip: 'icons.image' },
			{ icon: MaterialIcon.HEADPHONES, tooltip: 'icons.headphones' },
			{ icon: MaterialIcon.MUSIC_NOTE, tooltip: 'icons.musicNote' },
			{ icon: MaterialIcon.PIANO, tooltip: 'icons.piano' },
			{ icon: MaterialIcon.SPORTS_ESPORTS, tooltip: 'icons.gameController' },
			{ icon: MaterialIcon.EXTENSION, tooltip: 'icons.extension' },
			{ icon: MaterialIcon.CASINO, tooltip: 'icons.casino' },
			{ icon: MaterialIcon.THEATER_COMEDY, tooltip: 'icons.theater' },
			{ icon: MaterialIcon.BOOK, tooltip: 'icons.bookWithBookmark' },
			{ icon: MaterialIcon.SPORTS_SOCCER, tooltip: 'icons.football' },
			{ icon: MaterialIcon.SPORTS_BASKETBALL, tooltip: 'icons.basketball' },
			{ icon: MaterialIcon.SPORTS_TENNIS, tooltip: 'icons.tennis' },
			{ icon: MaterialIcon.HIKING, tooltip: 'icons.hiking' },
			{ icon: MaterialIcon.KAYAKING, tooltip: 'icons.kayaking' },
			{ icon: MaterialIcon.DECK, tooltip: 'icons.deck' },
			{ icon: MaterialIcon.EVENT_SEAT, tooltip: 'icons.eventSeat' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.FINANCES],
		icons: [
			{ icon: MaterialIcon.WORK, tooltip: 'icons.work' },
			{ icon: MaterialIcon.PAID, tooltip: 'icons.paid' },
			{ icon: MaterialIcon.PRICE_CHECK, tooltip: 'icons.priceCheck' },
			{ icon: MaterialIcon.MONEY_BAG, tooltip: 'icons.monneyBag' },
			{ icon: MaterialIcon.ACCOUNT_BALANCE, tooltip: 'icons.accountBalance' },
			{ icon: MaterialIcon.WALLET, tooltip: 'icons.wallet' },
			{ icon: MaterialIcon.ACCOUNT_BALANCE_WALLET, tooltip: 'icons.walletBalance' },
			{ icon: MaterialIcon.EURO, tooltip: 'icons.euro' },
			{ icon: MaterialIcon.ADD_CARD, tooltip: 'icons.addCard' },
			{ icon: MaterialIcon.FINANCE_CHIP, tooltip: 'icons.financeChip' },
			{ icon: MaterialIcon.CURRENCY_EXCHANGE, tooltip: 'icons.currencyExchange' },
			{ icon: MaterialIcon.TOLL, tooltip: 'icons.toll' },
			{ icon: MaterialIcon.TRENDING_UP, tooltip: 'icons.trendingUp' },
			{ icon: MaterialIcon.TRENDING_DOWN, tooltip: 'icons.trendingDown' },
			{ icon: MaterialIcon.PRICE_CHANGE, tooltip: 'icons.priceChange' },
			{ icon: MaterialIcon.PIE_CHART, tooltip: 'icons.pieChart' },
			{ icon: MaterialIcon.BAR_CHART, tooltip: 'icons.barChart' },
			{ icon: MaterialIcon.CALCULATE, tooltip: 'icons.calculate' },
			{ icon: MaterialIcon.RECEIPT_LONG, tooltip: 'icons.receiptLong' },
			{ icon: MaterialIcon.REQUEST_QUOTE, tooltip: 'icons.requestQuote' },
		],
	},
	{
		name: MATERIAL_ICON_CATEGORY_DATA[MaterialIconCategory.OTHERS],
		icons: [
			{ icon: MaterialIcon.EVENT, tooltip: 'icons.calendar' },
			{ icon: MaterialIcon.SCHEDULE, tooltip: 'icons.schedule' },
			{ icon: MaterialIcon.CELEBRATION, tooltip: 'icons.celebration' },
			{ icon: MaterialIcon.MAIL, tooltip: 'icons.mail' },
			{ icon: MaterialIcon.NOTIFICATIONS, tooltip: 'icons.bell' },
			{ icon: MaterialIcon.PUBLIC, tooltip: 'icons.globe' },
			{ icon: MaterialIcon.CLOUD, tooltip: 'icons.cloud' },
			{ icon: MaterialIcon.LOCK, tooltip: 'icons.lock' },
			{ icon: MaterialIcon.KEY, tooltip: 'icons.key' },
			{ icon: MaterialIcon.VERIFIED, tooltip: 'icons.verified' },
			{ icon: MaterialIcon.HELP, tooltip: 'icons.help' },
			{ icon: MaterialIcon.STAR, tooltip: 'icons.star' },
			{ icon: MaterialIcon.FAVORITE, tooltip: 'icons.heart' },
			{ icon: MaterialIcon.BOOKMARK, tooltip: 'icons.bookmark' },
			{ icon: MaterialIcon.FLAG, tooltip: 'icons.flag' },
			{ icon: MaterialIcon.BROWSE, tooltip: 'icons.browse' },
			{ icon: MaterialIcon.DESCRIPTION, tooltip: 'icons.description' },
			{ icon: MaterialIcon.BUILD, tooltip: 'icons.build' },
			{ icon: MaterialIcon.KEYBOARD, tooltip: 'icons.keyboard' },
			{ icon: MaterialIcon.CANCEL, tooltip: 'icons.cancel' },
		],
	},
];
