export enum MaterialIcon {
	// Food & Dining
	LOCAL_GROCERY_STORE = 'LOCAL_GROCERY_STORE',
	SHOPPING_BASKET = 'SHOPPING_BASKET',
	KITCHEN = 'KITCHEN',
	SKILLET = 'SKILLET',
	EGG = 'EGG',
	NUTRITION = 'NUTRITION',
	RESTAURANT = 'RESTAURANT',
	RESTAURANT_MENU = 'RESTAURANT_MENU',
	GROCERY = 'GROCERY',
	LUNCH_DINING = 'LUNCH_DINING',
	DINNER_DINING = 'DINNER_DINING',
	FASTFOOD = 'FASTFOOD',
	LOCAL_PIZZA = 'LOCAL_PIZZA',
	LOCAL_CAFE = 'LOCAL_CAFE',
	BAKERY_DINING = 'BAKERY_DINING',
	CAKE = 'CAKE',
	ICECREAM = 'ICECREAM',
	LOCAL_BAR = 'LOCAL_BAR',
	WINE_BAR = 'WINE_BAR',
	LIQUOR = 'LIQUOR',

	// Housing & Utilities
	HOME = 'HOME',
	HOUSE = 'HOUSE',
	APARTMENT = 'APARTMENT',
	COTTAGE = 'COTTAGE',
	GARAGE_HOME = 'GARAGE_HOME',
	BED = 'BED',
	CHAIR = 'CHAIR',
	CONSTRUCTION = 'CONSTRUCTION',
	PLUMBING = 'PLUMBING',
	ELECTRICAL_SERVICES = 'ELECTRICAL_SERVICES',
	MOP = 'MOP',
	LIGHTBULB = 'LIGHTBULB',
	BOLT = 'BOLT',
	WATER_DROP = 'WATER_DROP',
	MODE_HEAT = 'MODE_HEAT',
	THERMOMETER = 'THERMOMETER',
	ENERGY_SAVINGS_LEAF = 'ENERGY_SAVINGS_LEAF',
	RECYCLING = 'RECYCLING',
	ROUTER = 'ROUTER',
	WIFI = 'WIFI',

	// Transport & Travel
	DIRECTIONS_CAR = 'DIRECTIONS_CAR',
	MOTORCYCLE = 'MOTORCYCLE',
	SCOOTER = 'SCOOTER',
	PEDAL_BIKE = 'PEDAL_BIKE',
	LOCAL_GAS_STATION = 'LOCAL_GAS_STATION',
	EV_STATION = 'EV_STATION',
	LOCAL_PARKING = 'LOCAL_PARKING',
	AUTO_TOWING = 'AUTO_TOWING',
	LOCAL_TAXI = 'LOCAL_TAXI',
	AIRPORT_SHUTTLE = 'AIRPORT_SHUTTLE',
	DIRECTIONS_BUS = 'DIRECTIONS_BUS',
	COMMUTE = 'COMMUTE',
	TRAIN = 'TRAIN',
	SUBWAY = 'SUBWAY',
	TRAM = 'TRAM',
	DIRECTIONS_BOAT = 'DIRECTIONS_BOAT',
	FLIGHT = 'FLIGHT',
	AIRPLANE_TICKET = 'AIRPLANE_TICKET',
	TRANSIT_TICKET = 'TRANSIT_TICKET',
	MAP = 'MAP',

	// Shopping & Apparel
	STORE = 'STORE',
	SHOPPING_CART = 'SHOPPING_CART',
	SHOPPING_BAG = 'SHOPPING_BAG',
	SELL = 'SELL',
	PERCENT = 'PERCENT',
	RECEIPT = 'RECEIPT',
	CARD_GIFTCARD = 'CARD_GIFTCARD',
	SEND_MONEY = 'SEND_MONEY',
	APPAREL = 'APPAREL',
	CHECKROOM = 'CHECKROOM',
	STYLER = 'STYLER',
	LAUNDRY = 'LAUNDRY',
	EYEGLASSES = 'EYEGLASSES',
	WATCH = 'WATCH',
	DIAMOND = 'DIAMOND',
	BACKPACK = 'BACKPACK',
	UMBRELLA = 'UMBRELLA',
	SMARTPHONE = 'SMARTPHONE',
	LAPTOP = 'LAPTOP',
	PRINT = 'PRINT',

	// Health & Beauty
	LOCAL_HOSPITAL = 'LOCAL_HOSPITAL',
	MEDICAL_SERVICES = 'MEDICAL_SERVICES',
	HEALTH_AND_SAFETY = 'HEALTH_AND_SAFETY',
	EMERGENCY = 'EMERGENCY',
	LOCAL_PHARMACY = 'LOCAL_PHARMACY',
	MEDICATION = 'MEDICATION',
	VACCINES = 'VACCINES',
	HEALING = 'HEALING',
	MONITOR_HEART = 'MONITOR_HEART',
	DENTISTRY = 'DENTISTRY',
	PSYCHOLOGY = 'PSYCHOLOGY',
	CLEAN_HANDS = 'CLEAN_HANDS',
	WASH = 'WASH',
	BRUSH = 'BRUSH',
	FACE = 'FACE',
	CONTENT_CUT = 'CONTENT_CUT',
	SPA = 'SPA',
	SELF_IMPROVEMENT = 'SELF_IMPROVEMENT',
	FITNESS_CENTER = 'FITNESS_CENTER',
	POOL = 'POOL',

	// Family & Education
	FAMILY_RESTROOM = 'FAMILY_RESTROOM',
	PREGNANT_WOMAN = 'PREGNANT_WOMAN',
	DIVERSITY_3 = 'DIVERSITY_3',
	DIVERSITY_1 = 'DIVERSITY_1',
	CHILD_CARE = 'CHILD_CARE',
	BABY_CHANGING_STATION = 'BABY_CHANGING_STATION',
	STROLLER = 'STROLLER',
	CRIB = 'CRIB',
	CHILD_FRIENDLY = 'CHILD_FRIENDLY',
	ESCALATOR_WARNING = 'ESCALATOR_WARNING',
	TOYS = 'TOYS',
	VIDEOGAME_ASSET = 'VIDEOGAME_ASSET',
	CASTLE = 'CASTLE',
	SENTIMENT_SATISFIED = 'SENTIMENT_SATISFIED',
	PETS = 'PETS',
	CRUELTY_FREE = 'CRUELTY_FREE',
	ELDERLY = 'ELDERLY',
	SCHOOL = 'SCHOOL',
	MENU_BOOK = 'MENU_BOOK',
	HISTORY_2 = 'HISTORY_2',

	// Entertainment & Hobbies
	MOVIE = 'MOVIE',
	THEATERS = 'THEATERS',
	LIVE_TV = 'LIVE_TV',
	CAMERA_ALT = 'CAMERA_ALT',
	IMAGESMODE = 'IMAGESMODE',
	HEADPHONES = 'HEADPHONES',
	MUSIC_NOTE = 'MUSIC_NOTE',
	PIANO = 'PIANO',
	SPORTS_ESPORTS = 'SPORTS_ESPORTS',
	EXTENSION = 'EXTENSION',
	CASINO = 'CASINO',
	THEATER_COMEDY = 'THEATER_COMEDY',
	BOOK = 'BOOK',
	SPORTS_SOCCER = 'SPORTS_SOCCER',
	SPORTS_BASKETBALL = 'SPORTS_BASKETBALL',
	SPORTS_TENNIS = 'SPORTS_TENNIS',
	HIKING = 'HIKING',
	KAYAKING = 'KAYAKING',
	DECK = 'DECK',
	EVENT_SEAT = 'EVENT_SEAT',

	// Finances
	WORK = 'WORK',
	PAID = 'PAID',
	PRICE_CHECK = 'PRICE_CHECK',
	MONEY_BAG = 'MONEY_BAG',
	ACCOUNT_BALANCE = 'ACCOUNT_BALANCE',
	WALLET = 'WALLET',
	ACCOUNT_BALANCE_WALLET = 'ACCOUNT_BALANCE_WALLET',
	EURO = 'EURO',
	ADD_CARD = 'ADD_CARD',
	FINANCE_CHIP = 'FINANCE_CHIP',
	CURRENCY_EXCHANGE = 'CURRENCY_EXCHANGE',
	TOLL = 'TOLL',
	TRENDING_UP = 'TRENDING_UP',
	TRENDING_DOWN = 'TRENDING_DOWN',
	PRICE_CHANGE = 'PRICE_CHANGE',
	PIE_CHART = 'PIE_CHART',
	BAR_CHART = 'BAR_CHART',
	CALCULATE = 'CALCULATE',
	RECEIPT_LONG = 'RECEIPT_LONG',
	REQUEST_QUOTE = 'REQUEST_QUOTE',

	// Others
	EVENT = 'EVENT',
	SCHEDULE = 'SCHEDULE',
	CELEBRATION = 'CELEBRATION',
	MAIL = 'MAIL',
	NOTIFICATIONS = 'NOTIFICATIONS',
	PUBLIC = 'PUBLIC',
	CLOUD = 'CLOUD',
	LOCK = 'LOCK',
	KEY = 'KEY',
	VERIFIED = 'VERIFIED',
	HELP = 'HELP',
	STAR = 'STAR',
	FAVORITE = 'FAVORITE',
	BOOKMARK = 'BOOKMARK',
	FLAG = 'FLAG',
	BROWSE = 'BROWSE',
	DESCRIPTION = 'DESCRIPTION',
	BUILD = 'BUILD',
	KEYBOARD = 'KEYBOARD',
	CANCEL = 'CANCEL',
}

interface MaterialIconInfo {
	icon: MaterialIcon;
	tooltip: string;
}

enum MaterialIconCategory {
	FOOD_AND_DINING = 'Food & Dining',
	HOUSING_AND_UTILITIES = 'Housing & Utilities',
	TRANSPORT_AND_TRAVEL = 'Transport & Travel',
	SHOPPING_AND_APPAREL = 'Shopping & Apparel',
	HEALTH_AND_BEAUTY = 'Health & Beauty',
	FAMILY_AND_EDUCATION = 'Family & Education',
	ENTERTAINMENT_AND_HOBBIES = 'Entertainment & Hobbies',
	FINANCES = 'Finances',
	OTHERS = 'Others',
}

interface MaterialIconCategoryInfo {
	name: MaterialIconCategory;
	icons: MaterialIconInfo[];
}

export const CategorizedMaterialIcons: MaterialIconCategoryInfo[] = [
	{
		name: MaterialIconCategory.FOOD_AND_DINING,
		icons: [
			{ icon: MaterialIcon.LOCAL_GROCERY_STORE, tooltip: 'shopping cart' },
			{ icon: MaterialIcon.SHOPPING_BASKET, tooltip: 'shopping basket' },
			{ icon: MaterialIcon.KITCHEN, tooltip: 'fridge' },
			{ icon: MaterialIcon.SKILLET, tooltip: 'skillet' },
			{ icon: MaterialIcon.EGG, tooltip: 'egg' },
			{ icon: MaterialIcon.NUTRITION, tooltip: 'nutrition' },
			{ icon: MaterialIcon.RESTAURANT, tooltip: 'restaurant' },
			{ icon: MaterialIcon.RESTAURANT_MENU, tooltip: 'menu' },
			{ icon: MaterialIcon.GROCERY, tooltip: 'groceries' },
			{ icon: MaterialIcon.LUNCH_DINING, tooltip: 'lunch' },
			{ icon: MaterialIcon.DINNER_DINING, tooltip: 'dinner' },
			{ icon: MaterialIcon.FASTFOOD, tooltip: 'fastfood' },
			{ icon: MaterialIcon.LOCAL_PIZZA, tooltip: 'pizza' },
			{ icon: MaterialIcon.LOCAL_CAFE, tooltip: 'cafe' },
			{ icon: MaterialIcon.BAKERY_DINING, tooltip: 'bakery' },
			{ icon: MaterialIcon.CAKE, tooltip: 'cake' },
			{ icon: MaterialIcon.ICECREAM, tooltip: 'ice cream' },
			{ icon: MaterialIcon.LOCAL_BAR, tooltip: 'bar' },
			{ icon: MaterialIcon.WINE_BAR, tooltip: 'wine bar' },
			{ icon: MaterialIcon.LIQUOR, tooltip: 'liquor' },
		],
	},
	{
		name: MaterialIconCategory.HOUSING_AND_UTILITIES,
		icons: [
			{ icon: MaterialIcon.HOME, tooltip: 'home' },
			{ icon: MaterialIcon.HOUSE, tooltip: 'house' },
			{ icon: MaterialIcon.APARTMENT, tooltip: 'apartment' },
			{ icon: MaterialIcon.COTTAGE, tooltip: 'cottage' },
			{ icon: MaterialIcon.GARAGE_HOME, tooltip: 'garage' },
			{ icon: MaterialIcon.BED, tooltip: 'bed' },
			{ icon: MaterialIcon.CHAIR, tooltip: 'chair' },
			{ icon: MaterialIcon.CONSTRUCTION, tooltip: 'construction' },
			{ icon: MaterialIcon.PLUMBING, tooltip: 'plumbing' },
			{ icon: MaterialIcon.ELECTRICAL_SERVICES, tooltip: 'electrical services' },
			{ icon: MaterialIcon.MOP, tooltip: 'mop' },
			{ icon: MaterialIcon.LIGHTBULB, tooltip: 'lightbulb' },
			{ icon: MaterialIcon.BOLT, tooltip: 'bolt' },
			{ icon: MaterialIcon.WATER_DROP, tooltip: 'water drop' },
			{ icon: MaterialIcon.MODE_HEAT, tooltip: 'fire' },
			{ icon: MaterialIcon.THERMOMETER, tooltip: 'thermometer' },
			{ icon: MaterialIcon.ENERGY_SAVINGS_LEAF, tooltip: 'energy saving leaf' },
			{ icon: MaterialIcon.RECYCLING, tooltip: 'recycling' },
			{ icon: MaterialIcon.ROUTER, tooltip: 'router' },
			{ icon: MaterialIcon.WIFI, tooltip: 'wifi' },
		],
	},
	{
		name: MaterialIconCategory.TRANSPORT_AND_TRAVEL,
		icons: [
			{ icon: MaterialIcon.DIRECTIONS_CAR, tooltip: 'car' },
			{ icon: MaterialIcon.MOTORCYCLE, tooltip: 'motorcycle' },
			{ icon: MaterialIcon.SCOOTER, tooltip: 'scrooter' },
			{ icon: MaterialIcon.PEDAL_BIKE, tooltip: 'pedal bike' },
			{ icon: MaterialIcon.LOCAL_GAS_STATION, tooltip: 'gas station' },
			{ icon: MaterialIcon.EV_STATION, tooltip: 'electric charger' },
			{ icon: MaterialIcon.LOCAL_PARKING, tooltip: 'parking' },
			{ icon: MaterialIcon.AUTO_TOWING, tooltip: 'towing' },
			{ icon: MaterialIcon.LOCAL_TAXI, tooltip: 'taxi' },
			{ icon: MaterialIcon.AIRPORT_SHUTTLE, tooltip: 'airport shuttle' },
			{ icon: MaterialIcon.DIRECTIONS_BUS, tooltip: 'bus' },
			{ icon: MaterialIcon.COMMUTE, tooltip: 'commute' },
			{ icon: MaterialIcon.TRAIN, tooltip: 'train' },
			{ icon: MaterialIcon.SUBWAY, tooltip: 'subway' },
			{ icon: MaterialIcon.TRAM, tooltip: 'tram' },
			{ icon: MaterialIcon.DIRECTIONS_BOAT, tooltip: 'boat' },
			{ icon: MaterialIcon.FLIGHT, tooltip: 'flight' },
			{ icon: MaterialIcon.AIRPLANE_TICKET, tooltip: 'airplane ticket' },
			{ icon: MaterialIcon.TRANSIT_TICKET, tooltip: 'transit ticket' },
			{ icon: MaterialIcon.MAP, tooltip: 'map' },
		],
	},
	{
		name: MaterialIconCategory.SHOPPING_AND_APPAREL,
		icons: [
			{ icon: MaterialIcon.STORE, tooltip: 'store' },
			{ icon: MaterialIcon.SHOPPING_CART, tooltip: 'shopping cart' },
			{ icon: MaterialIcon.SHOPPING_BAG, tooltip: 'shopping bag' },
			{ icon: MaterialIcon.SELL, tooltip: 'price tag' },
			{ icon: MaterialIcon.PERCENT, tooltip: 'percent' },
			{ icon: MaterialIcon.RECEIPT, tooltip: 'receipt' },
			{ icon: MaterialIcon.CARD_GIFTCARD, tooltip: 'giftcard' },
			{ icon: MaterialIcon.SEND_MONEY, tooltip: 'send money' },
			{ icon: MaterialIcon.APPAREL, tooltip: 'apparel' },
			{ icon: MaterialIcon.CHECKROOM, tooltip: 'checkroom' },
			{ icon: MaterialIcon.STYLER, tooltip: 'styler' },
			{ icon: MaterialIcon.LAUNDRY, tooltip: 'laundry' },
			{ icon: MaterialIcon.EYEGLASSES, tooltip: 'glasses' },
			{ icon: MaterialIcon.WATCH, tooltip: 'watch' },
			{ icon: MaterialIcon.DIAMOND, tooltip: 'diamond' },
			{ icon: MaterialIcon.BACKPACK, tooltip: 'backpack' },
			{ icon: MaterialIcon.UMBRELLA, tooltip: 'umbrella' },
			{ icon: MaterialIcon.SMARTPHONE, tooltip: 'smartphone' },
			{ icon: MaterialIcon.LAPTOP, tooltip: 'laptop' },
			{ icon: MaterialIcon.PRINT, tooltip: 'printer' },
		],
	},
	{
		name: MaterialIconCategory.HEALTH_AND_BEAUTY,
		icons: [
			{ icon: MaterialIcon.LOCAL_HOSPITAL, tooltip: 'hospital' },
			{ icon: MaterialIcon.MEDICAL_SERVICES, tooltip: 'medial services' },
			{ icon: MaterialIcon.HEALTH_AND_SAFETY, tooltip: 'health' },
			{ icon: MaterialIcon.EMERGENCY, tooltip: 'emergency' },
			{ icon: MaterialIcon.LOCAL_PHARMACY, tooltip: 'pharmacy' },
			{ icon: MaterialIcon.MEDICATION, tooltip: 'medication' },
			{ icon: MaterialIcon.VACCINES, tooltip: 'vaccines' },
			{ icon: MaterialIcon.HEALING, tooltip: 'patches' },
			{ icon: MaterialIcon.MONITOR_HEART, tooltip: 'heart monitor' },
			{ icon: MaterialIcon.DENTISTRY, tooltip: 'tooth' },
			{ icon: MaterialIcon.PSYCHOLOGY, tooltip: 'psychology' },
			{ icon: MaterialIcon.CLEAN_HANDS, tooltip: 'handwash' },
			{ icon: MaterialIcon.WASH, tooltip: 'wash' },
			{ icon: MaterialIcon.BRUSH, tooltip: 'brush' },
			{ icon: MaterialIcon.FACE, tooltip: 'face' },
			{ icon: MaterialIcon.CONTENT_CUT, tooltip: 'scissors' },
			{ icon: MaterialIcon.SPA, tooltip: 'spa' },
			{ icon: MaterialIcon.SELF_IMPROVEMENT, tooltip: 'mediation' },
			{ icon: MaterialIcon.FITNESS_CENTER, tooltip: 'dumbbell' },
			{ icon: MaterialIcon.POOL, tooltip: 'swim' },
		],
	},
	{
		name: MaterialIconCategory.FAMILY_AND_EDUCATION,
		icons: [
			{ icon: MaterialIcon.FAMILY_RESTROOM, tooltip: 'family' },
			{ icon: MaterialIcon.PREGNANT_WOMAN, tooltip: 'pregnant woman' },
			{ icon: MaterialIcon.DIVERSITY_3, tooltip: 'closeup family' },
			{ icon: MaterialIcon.DIVERSITY_1, tooltip: 'family heart' },
			{ icon: MaterialIcon.CHILD_CARE, tooltip: 'child' },
			{ icon: MaterialIcon.BABY_CHANGING_STATION, tooltip: 'baby changing station' },
			{ icon: MaterialIcon.STROLLER, tooltip: 'stroller' },
			{ icon: MaterialIcon.CRIB, tooltip: 'crib' },
			{ icon: MaterialIcon.CHILD_FRIENDLY, tooltip: 'child friendly' },
			{ icon: MaterialIcon.ESCALATOR_WARNING, tooltip: 'family of 2' },
			{ icon: MaterialIcon.TOYS, tooltip: 'toy' },
			{ icon: MaterialIcon.VIDEOGAME_ASSET, tooltip: 'old game controller' },
			{ icon: MaterialIcon.CASTLE, tooltip: 'castle' },
			{ icon: MaterialIcon.SENTIMENT_SATISFIED, tooltip: 'smile' },
			{ icon: MaterialIcon.PETS, tooltip: 'pet' },
			{ icon: MaterialIcon.CRUELTY_FREE, tooltip: 'bunny' },
			{ icon: MaterialIcon.ELDERLY, tooltip: 'elderly' },
			{ icon: MaterialIcon.SCHOOL, tooltip: 'education' },
			{ icon: MaterialIcon.MENU_BOOK, tooltip: 'book' },
			{ icon: MaterialIcon.HISTORY_2, tooltip: 'time' },
		],
	},
	{
		name: MaterialIconCategory.ENTERTAINMENT_AND_HOBBIES,
		icons: [
			{ icon: MaterialIcon.MOVIE, tooltip: 'movie' },
			{ icon: MaterialIcon.THEATERS, tooltip: 'theater symbol' },
			{ icon: MaterialIcon.LIVE_TV, tooltip: 'tv' },
			{ icon: MaterialIcon.CAMERA_ALT, tooltip: 'camera' },
			{ icon: MaterialIcon.IMAGESMODE, tooltip: 'image' },
			{ icon: MaterialIcon.HEADPHONES, tooltip: 'headphones' },
			{ icon: MaterialIcon.MUSIC_NOTE, tooltip: 'music note' },
			{ icon: MaterialIcon.PIANO, tooltip: 'piano' },
			{ icon: MaterialIcon.SPORTS_ESPORTS, tooltip: 'game controller' },
			{ icon: MaterialIcon.EXTENSION, tooltip: 'extension' },
			{ icon: MaterialIcon.CASINO, tooltip: 'casino' },
			{ icon: MaterialIcon.THEATER_COMEDY, tooltip: 'theater' },
			{ icon: MaterialIcon.BOOK, tooltip: 'book with bookmark' },
			{ icon: MaterialIcon.SPORTS_SOCCER, tooltip: 'football' },
			{ icon: MaterialIcon.SPORTS_BASKETBALL, tooltip: 'basketball' },
			{ icon: MaterialIcon.SPORTS_TENNIS, tooltip: 'tennis' },
			{ icon: MaterialIcon.HIKING, tooltip: 'hiking' },
			{ icon: MaterialIcon.KAYAKING, tooltip: 'kayaking' },
			{ icon: MaterialIcon.DECK, tooltip: 'deck' },
			{ icon: MaterialIcon.EVENT_SEAT, tooltip: 'event seat' },
		],
	},
	{
		name: MaterialIconCategory.FINANCES,
		icons: [
			{ icon: MaterialIcon.WORK, tooltip: 'work' },
			{ icon: MaterialIcon.PAID, tooltip: 'paid' },
			{ icon: MaterialIcon.PRICE_CHECK, tooltip: 'price check' },
			{ icon: MaterialIcon.MONEY_BAG, tooltip: 'monney bag' },
			{ icon: MaterialIcon.ACCOUNT_BALANCE, tooltip: 'account balance' },
			{ icon: MaterialIcon.WALLET, tooltip: 'wallet' },
			{ icon: MaterialIcon.ACCOUNT_BALANCE_WALLET, tooltip: 'wallet balance' },
			{ icon: MaterialIcon.EURO, tooltip: 'euro' },
			{ icon: MaterialIcon.ADD_CARD, tooltip: 'add card' },
			{ icon: MaterialIcon.FINANCE_CHIP, tooltip: 'finance chip' },
			{ icon: MaterialIcon.CURRENCY_EXCHANGE, tooltip: 'currency exchange' },
			{ icon: MaterialIcon.TOLL, tooltip: 'toll' },
			{ icon: MaterialIcon.TRENDING_UP, tooltip: 'trending up' },
			{ icon: MaterialIcon.TRENDING_DOWN, tooltip: 'trending down' },
			{ icon: MaterialIcon.PRICE_CHANGE, tooltip: 'price change' },
			{ icon: MaterialIcon.PIE_CHART, tooltip: 'pie chart' },
			{ icon: MaterialIcon.BAR_CHART, tooltip: 'bar chart' },
			{ icon: MaterialIcon.CALCULATE, tooltip: 'calculate' },
			{ icon: MaterialIcon.RECEIPT_LONG, tooltip: 'receipt long' },
			{ icon: MaterialIcon.REQUEST_QUOTE, tooltip: 'request quote' },
		],
	},
	{
		name: MaterialIconCategory.OTHERS,
		icons: [
			{ icon: MaterialIcon.EVENT, tooltip: 'calendar' },
			{ icon: MaterialIcon.SCHEDULE, tooltip: 'schedule' },
			{ icon: MaterialIcon.CELEBRATION, tooltip: 'celebration' },
			{ icon: MaterialIcon.MAIL, tooltip: 'mail' },
			{ icon: MaterialIcon.NOTIFICATIONS, tooltip: 'bell' },
			{ icon: MaterialIcon.PUBLIC, tooltip: 'globe' },
			{ icon: MaterialIcon.CLOUD, tooltip: 'cloud' },
			{ icon: MaterialIcon.LOCK, tooltip: 'lock' },
			{ icon: MaterialIcon.KEY, tooltip: 'key' },
			{ icon: MaterialIcon.VERIFIED, tooltip: 'verified' },
			{ icon: MaterialIcon.HELP, tooltip: 'help' },
			{ icon: MaterialIcon.STAR, tooltip: 'star' },
			{ icon: MaterialIcon.FAVORITE, tooltip: 'heart' },
			{ icon: MaterialIcon.BOOKMARK, tooltip: 'bookmark' },
			{ icon: MaterialIcon.FLAG, tooltip: 'flag' },
			{ icon: MaterialIcon.BROWSE, tooltip: 'browse' }, // TODO remove (we use this)
			{ icon: MaterialIcon.DESCRIPTION, tooltip: 'description' },
			{ icon: MaterialIcon.BUILD, tooltip: 'build' },
			{ icon: MaterialIcon.KEYBOARD, tooltip: 'keyboard' },
			{ icon: MaterialIcon.CANCEL, tooltip: 'cancel' },
		],
	},
];
