export enum AuditableEntityType {
	TRANSACTION = 'TRANSACTION',
	CATEGORY = 'CATEGORY',
	GOAL = 'GOAL',
	DEBT = 'DEBT',
	INVESTMENT = 'INVESTMENT',
	RECURRING_TRANSACTION = 'RECURRING_TRANSACTION',
	WORKSPACE = 'WORKSPACE',
	WORKSPACE_MEMBER = 'WORKSPACE_MEMBER',
}
