name: exence
services:
  exence-pg:
    image: postgres:16
    container_name: exence-postgres
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-exencedev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-exencepwd}
      POSTGRES_DB: ${DB_NAME:-exence_db}

  maildev:
    image: maildev/maildev
    container_name: exence-maildev
    restart: always
    ports:
      - "6808:1080"  # Web UI
      - "6800:1025"  # SMTP server
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025

volumes:
  pgdata: