package com.exence.finance.modules.statistics.dto.goal;

public enum GoalWidgetType {
    GOAL_ACTIVE_COUNT_STATCARD,
    GOAL_AVG_PROGRESS_STATCARD,
    GOAL_COMPLETION_RATE_STATCARD,
    GOAL_NEXT_DEADLINE_STATCARD,
    GOAL_PROGRESS_TREND,
    GOAL_TARGET_DISTRIBUTION_PIE,
    GOAL_TOTAL_SAVED_THIS_YEAR_STATCARD,
    GOAL_TOTAL_SAVINGS_STATCARD
}
