name: Backend CI

on:
  pull_request:
    branches: [develop, main]
    paths: ['backend/**', '.github/workflows/backend-ci.yml']
  push:
    branches: [develop]
    paths: ['backend/**', '.github/workflows/backend-ci.yml']

env:
  MAVEN_OPTS: -Xmx1024m

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: exence_test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: backend/exence

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Maven wrapper
        run: chmod +x ./mvnw

      - name: Run tests
        run: ./mvnw -B clean test
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/exence_test
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test

      - name: Run security scan with SpotBugs
        run: ./mvnw spotbugs:check
        continue-on-error: true

      - name: Build application
        run: ./mvnw -B clean package -DskipTests

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: backend/exence/target/surefire-reports/

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: backend/exence/target/site/jacoco/
