name: Frontend CI

on:
  pull_request:
    branches: [develop, main]
    paths: ['frontend/**', '.github/workflows/frontend-ci.yml']
  push:
    branches: [develop]
    paths: ['frontend/**', '.github/workflows/frontend-ci.yml']

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/Exence

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/Exence/package-lock.json'

      - name: Install dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npm run lint

      - name: Build application
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run e2e

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/Exence/playwright-report/
          retention-days: 30
